### ISSUE TITLE
Too much data

### ISSUE THREAD

**Issue by FZDNSZYT** [PlayPro/CoreProtect#220]
Is it possible to add a function to periodically clean up old data, the amount of data is getting bigger and bigger, I am worried that the server disk will not be able to hold it. Because I'm running a survival server and I've added some custom components.

**Comment by vacla** [comment]
@FZDNSZYT you can purge the database from time to time, check https://docs.coreprotect.net/commands/#co-purge for more info, you can also make a cron command if needed.

**Comment by EscolarProgramming** [comment]
@vacla It is tedious to purge by hand, because you don't always think about it and it can result in large amounts of data. Above a certain size, purge is almost impossible because it takes forever. And not everyone has a freely configurable server on which they can create cron jobs themselves.

We forgot about it for a few months and ended up with a database size of almost 40GB. For example, if you can set it to automatically delete all data older than 30 days when the server is started, this would be much easier and more useful.

**Comment by Sebas-Re** [comment]
This sounds like a very cool feature suggestion

**Comment by Intelli** [comment]
Duplicate of #176
